### ISSUE TITLE
Add support to span

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#31]
Users should be able to retrieve the code span of SMIR items.

**Comment by oli-obk** [comment]
how should we expose it. If we expose it directly (have `PathBuf`, line/col info and expansion info directly in the `smir::Span` struct), that may get expensive. If we expose it indirectly, we can do it like `.kind()` on `smir::Ty`, computing it only when requested and otherwise just storing an index.

**Comment by celinval** [comment]
We should encapsulate the path, so no one relies on having direct access to them. We probably want to intern the pathbuf for the file, so we don't keep replicating it.

**Comment by ouz-a** [comment]
Should we return `rustc_span::Span` or `stable_mir::Span`, agree with oli here exposing indirectly will suffice for most needs.

**Comment by ouz-a** [comment]
can we close this now ?

**Comment by oli-obk** [comment]
Right now the spans are opaque and thus not very useful. We should add a way to retrieve file, line, col and expansion information.
